version: '2.2'

services:
  database:
    environment:
      POSTGRES_PASSWORD: "klaxon"
  web:
    build:
      args:
        RAILS_ENV: "production"
    environment:
      RACK_ENV: "production"
      RAILS_ENV: "production"
      DB_PORT: "5432"
      DB_HOST: "database"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "klaxon"
      DB_NAME: "klaxon"
      ADMIN_EMAILS: "tcardoso@globeandmail.com"
