version: '2.2'

services:
  database:
    environment:
      POSTGRES_PASSWORD: "klaxon"
  web:
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      PGPORT: "5432"
      PGHOST: "database"
      PGUSER: "postgres"
      PGPASSWORD: "klaxon"
      PGDBNAME: "klaxon"
      ADMIN_EMAILS: "tcardoso@globeandmail.com"
      KLAXON_FORCE_SSL: "false"
