version: '2.2'

services:
  database:
    environment:
      POSTGRES_PASSWORD: "klaxon"
  web:
    build:
      args:
        RAILS_ENV: "production"
    environment:
      RACK_ENV: "production"
      RAILS_ENV: "production"
      PGPORT: "5432"
      PGHOST: "database"
      PGUSER: "postgres"
      PGPASSWORD: "klaxon"
      PGDBNAME: "klaxon"
      ADMIN_EMAILS: "tcardoso@globeandmail.com"
