version: '2.2'
services:
  database:
    image: "postgres:9.6"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/klaxon"
    ports:
      - "3000:3000"
    environment:
      APP_HOME: "/klaxon"
      # Klaxon-specific
      ADMIN_EMAILS:
      # Rails stuff
      RAILS_ENV:
      RACK_ENV:
      SECRET_KEY_BASE:
      RAILS_LOG_TO_STDOUT:
      RAILS_SERVE_STATIC_FILES:
      # Database-specific stuff
      PGPORT:
      PGHOST:
      PGUSER:
      PGPASSWORD:
      PGDBNAME:
      # For AWS secrets manager, if using
      AWS_SECRETS_PREFIX:
      AWS_REGION:
      # SENDGRID or SES
      SMTP_PROVIDER:
      # Sendgrid
      SENDGRID_USERNAME:
      SENDGRID_PASSWORD:
      # SES
      SES_ADDRESS:
      SES_USERNAME:
      SES_PASSWORD:
      SES_DOMAIN:
      SES_PORT:
      MAILER_FROM_ADDRESS:
    depends_on:
      database:
        condition: service_healthy
